#!/bin/bash

export MEESEEKS_HOME=`dirname $0`/..

export PATH=$PATH:$MEESEEKS_HOME/bin
export PYTHONPATH=$MEESEEKS_HOME/lib

exec meeseeks-box $MEESEEKS_HOME/etc/global.cfg $MEESEEKS_HOME/etc/$HOSTNAME.cfg